// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0mZG9aIYhaIb6G7aG1TN8JVAbT_a-9KU',
    appId: '1:868777939072:web:639902847fa65061905665',
    messagingSenderId: '868777939072',
    projectId: 'flutter-hf-firebase',
    authDomain: 'flutter-hf-firebase.firebaseapp.com',
    storageBucket: 'flutter-hf-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhD4STxwjj1H0tDS6rkapCydAXbYksEQ8',
    appId: '1:868777939072:android:786d369d55406641905665',
    messagingSenderId: '868777939072',
    projectId: 'flutter-hf-firebase',
    storageBucket: 'flutter-hf-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHB9_cPOlOYJ1ZzGxJ-KUGK9HtkgjGabI',
    appId: '1:868777939072:ios:6030c5b69ae85b13905665',
    messagingSenderId: '868777939072',
    projectId: 'flutter-hf-firebase',
    storageBucket: 'flutter-hf-firebase.appspot.com',
    iosClientId: '868777939072-r85ris25ugfa07ttagndm93me40en3cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.hf',
  );
}
